server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always

springdoc:
  show-actuator: true
  swagger-ui:
    operationsSorter: method

app:
  locale:
    default: ${LOCALE_DEFAULT:es}
    cookie:
      name: ${LOCALE_COOKIE_NAME:lang}

  security:
    ignore-paths:
      all: "/actuator/**,/v3/api-docs/**,/swagger-ui/**,/api/config/lang/**,/api/auth/signup,/api/auth/login,/api/auth/refresh"
      get: "/api/account/role/supported"

    cors:
      allowed-origins: ${SECURITY_CORS_ALLOWED_ORIGINS:*}
      allowed-methods: ${SECURITY_CORS_ALLOWED_METHODS:GET,POST,PUT,PATCH,DELETE,OPTIONS}
      allowed-headers: ${SECURITY_CORS_ALLOWED_HEADERS:Content-Type,Authorization,Accept,Origin,X-Requested-With}
      exposed-headers: ${SECURITY_CORS_EXPOSED_HEADERS:Authorization,Token}
      allow-credentials: ${SECURITY_CORS_ALLOW_CREDENTIALS:true}

    token:
      access-token:
        secret: ${SECURITY_TOKEN_ACCESS_TOKEN_SECRET}
        expiration: ${SECURITY_TOKEN_ACCESS_TOKEN_EXPIRATION:180000} # 3 minutes in milliseconds
        name: ${SECURITY_TOKEN_ACCESS_TOKEN_NAME:Token}

    refresh-token:
      secret: ${SECURITY_TOKEN_REFRESH_TOKEN_SECRET}
      expiration: ${SECURITY_TOKEN_REFRESH_TOKEN_EXPIRATION:604800000} # 7 days in milliseconds
      name: ${SECURITY_TOKEN_REFRESH_TOKEN_NAME:Refresh-Token}

spring:
  application:
    name: rest-server

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT:5432}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        type:
          preferred_uuid_jdbc_type: UUID
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true

  messages:
    basename: i18n/messages
    encoding: UTF-8

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB