CREATE TABLE users (
    id UUID PRIMARY KEY,
    role INT4 NOT NULL,
    username VARCHAR( 25 ) NOT NULL UNIQUE,
    name VARCHAR( 50 ) NOT NULL,
    surname VARCHAR( 50 ),
    birthdate DATE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE accounts (
    id UUID PRIMARY KEY,
    owner UUID NOT NULL,
    email VARCHAR( 256 ) NOT NULL UNIQUE,
    password VARCHAR( 256 ) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ( owner ) REFERENCES users( id ) ON DELETE CASCADE ON UPDATE CASCADE
);