CREATE TABLE users (
    id UUID PRIMARY KEY,
    username VARCHAR( 25 ) NOT NULL UNIQUE,
    name VARCHAR( 50 ) NOT NULL,
    surname VARCHAR( 50 ),
    birthdate DATE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE accounts (
    id UUID PRIMARY KEY,
    owner UUID NOT NULL,
    lang VARCHAR( 10 ),
    role INT4 NOT NULL,
    email VARCHAR( 256 ) NOT NULL UNIQUE,
    password VARCHAR( 256 ) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ( owner ) REFERENCES users( id ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE security_tokens (
    id UUID PRIMARY KEY,
    version UUID NOT NULL UNIQUE,
    account UUID NOT NULL,
    ip VARCHAR( 256 ),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ( account ) REFERENCES accounts( id ) ON DELETE CASCADE ON UPDATE CASCADE
);